apiVersion: apps/v1
kind: Deployment
metadata:
  name: algohive-db
  namespace: algohive
  labels:
    app: algohive-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algohive-db
  template:
    metadata:
      labels:
        app: algohive-db
    spec:
      containers:
      - name: postgres
        image: postgres:17-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: TZ
          value: "Europe/Paris"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: algohive-db
  namespace: algohive
spec:
  selector:
    app: algohive-db
  ports:
  - port: 5432
    targetPort: 5432
