apiVersion: apps/v1
kind: Deployment
metadata:
  name: beehub
  namespace: algohive
  labels:
    app: beehub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beehub
  template:
    metadata:
      labels:
        app: beehub
    spec:
      containers:
      - name: beehub
        image: ghcr.io/algohive-coding-puzzles/beehub:latest
        ports:
        - containerPort: 8081
        env:
        - name: TZ
          value: "Europe/Paris"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: beehub-credentials
              key: SECRET_KEY
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: beehub-credentials
              key: ADMIN_USERNAME
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: beehub-credentials
              key: ADMIN_PASSWORD
        envFrom:
        - configMapRef:
            name: beehub-config
        volumeMounts:
        - name: beehub-db
          mountPath: /app/backend/db
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: beehub-db
        persistentVolumeClaim:
          claimName: beehub-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: beehub
  namespace: algohive
spec:
  selector:
    app: beehub
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30082
  type: NodePort
