apiVersion: apps/v1
kind: Deployment
metadata:
  name: algohive-server
  namespace: algohive
  labels:
    app: algohive-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: algohive-server
  template:
    metadata:
      labels:
        app: algohive-server
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z algohive-db 5432; do echo waiting for postgres; sleep 2; done']
      - name: wait-for-cache
        image: busybox:1.36
        command: ['sh', '-c', 'until nc -z algohive-cache 6379; do echo waiting for redis; sleep 2; done']
      containers:
      - name: server
        image: ghcr.io/algohive-coding-puzzles/api:latest
        ports:
        - containerPort: 8080
        env:
        - name: TZ
          value: "Europe/Paris"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
        envFrom:
        - configMapRef:
            name: algohive-server-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: algohive-server
  namespace: algohive
spec:
  selector:
    app: algohive-server
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
