apiVersion: apps/v1
kind: Deployment
metadata:
  name: algohive-client
  namespace: algohive
  labels:
    app: algohive-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: algohive-client
  template:
    metadata:
      labels:
        app: algohive-client
    spec:
      containers:
      - name: client
        image: ghcr.io/algohive-coding-puzzles/client:latest
        ports:
        - containerPort: 80
        env:
        - name: TZ
          value: "Europe/Paris"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: algohive-client
  namespace: algohive
spec:
  selector:
    app: algohive-client
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
