# =============================================================================
# Kube-Flannel - ServiceAccount
# =============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flannel
  namespace: kube-flannel
  labels:
    k8s-app: flannel
