# =============================================================================
# OpenEBS - Namespace
# =============================================================================
---
apiVersion: v1
kind: Namespace
metadata:
  name: openebs
  labels:
    openebs.io/version: 3.5.0
