# =============================================================================
# OpenEBS - ServiceAccount
# =============================================================================
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openebs-maya-operator
  namespace: openebs
