# =============================================================================
# OpenEBS - Services (exposition des métriques Prometheus)
# =============================================================================
---
apiVersion: v1
kind: Service
metadata:
  name: openebs-ndm-cluster-exporter-service
  namespace: openebs
  labels:
    app: openebs-ndm-exporter
    name: openebs-ndm-cluster-exporter-service
    openebs.io/component-name: ndm-cluster-exporter
spec:
  clusterIP: None
  selector:
    name: openebs-ndm-cluster-exporter
  ports:
  - name: metrics
    port: 9100
    targetPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: openebs-ndm-node-exporter-service
  namespace: openebs
  labels:
    app: openebs-ndm-exporter
    name: openebs-ndm-node-exporter
    openebs.io/component: openebs-ndm-node-exporter
spec:
  clusterIP: None
  selector:
    name: openebs-ndm-node-exporter
  ports:
  - name: metrics
    port: 9101
    targetPort: 9101
