apiVersion: v1
kind: Secret
metadata:
  name: monitoring-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/instance: monitoring
    app.kubernetes.io/name: grafana
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: S1NDYll1MkVBd09kbm1RNHNXaUdoNzlWU3Q1MEVGSVcxQU1YY0pFTg==
