# =============================================================================
# MetalLB Service Accounts
# =============================================================================
# Ces ServiceAccounts permettent aux pods MetalLB d'interagir avec l'API
# Kubernetes de manière sécurisée.
#
# - controller: Utilisé par le deployment controller pour gérer les IPs
# - speaker: Utilisé par le daemonset speaker pour annoncer les IPs sur le réseau
# =============================================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller
  namespace: metallb-system
  labels:
    app: metallb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: speaker
  namespace: metallb-system
  labels:
    app: metallb
