# =============================================================================
# MetalLB IPAddressPool — template, rendu via envsubst depuis cluster.env
# Usage : envsubst < 10-ipaddresspool.yaml | kubectl apply -f -
#
# Variables requises (définies dans cluster.env) :
#   LB_POOL_START  → adresse de début de la plage (ex: 192.168.1.100)
#   LB_POOL_END    → adresse de fin de la plage   (ex: 192.168.1.105)
#
# IMPORTANT: Assurez-vous que ces IPs ne sont pas utilisées par d'autres
# équipements sur votre réseau (hors plage DHCP).
# =============================================================================

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - ${LB_POOL_START}-${LB_POOL_END}
  autoAssign: true
