# =============================================================================
# Ingress NGINX Services
# =============================================================================
# Deux services sont nécessaires:
#
# 1. ingress-nginx-controller (LoadBalancer)
#    - Expose le controller sur les ports 80 (HTTP) et 443 (HTTPS)
#    - Reçoit une IP externe via MetalLB (192.168.1.100)
#    - Point d'entrée principal pour tout le trafic HTTP/HTTPS
#
# 2. ingress-nginx-controller-admission (ClusterIP)
#    - Service interne pour le webhook de validation
#    - Utilisé par l'API Server pour valider les Ingress
# =============================================================================

apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: "1.11.1"
spec:
  type: LoadBalancer
  # Pour demander une IP spécifique via MetalLB:
  # loadBalancerIP: 192.168.1.100
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
      appProtocol: http
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
      appProtocol: https
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-admission
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: "1.11.1"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/component: controller
  ports:
    - name: https-webhook
      port: 443
      targetPort: webhook
      appProtocol: https
